import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Flowbite } from "flowbite-react";
import { customTheme } from "@/lib/customTheme";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400"],
	variable: "--font-poppins",
});

export const metadata = {
	title: "PTMS",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`${inter.className} ${poppins.className} `}>
				<Flowbite theme={{ theme: customTheme }}>{children}</Flowbite>
			</body>
		</html>
	);
}
